#!/usr/bin/env node

import {
  applyDefaultPatchArgs,
  builderRoot,
  env,
  isMainScript,
  parseTargets,
  runMorphe,
  validateTargets,
} from "./builder-common.mjs";
import { externalPatchAppConfigs } from "./morphe.mjs";

const root = builderRoot(import.meta.url);
const command = process.argv[2] || "build";
const args = process.argv.slice(3);
const isMain = isMainScript(import.meta.url);

const supportedTargets = new Set([
  "adguard",
  "alltrails",
  "avocards",
  "busuu",
  "cake",
  "camscanner",
  "daily-pocket",
  "duolingo",
  "eggbun",
  "fotmob",
  "github",
  "hellochinese",
  "ibispaint-x",
  "icon-packer",
  "lingory",
  "lyfta",
  "macrofactor",
  "macrofactor-workouts",
  "meme-generator",
  "merriam-webster",
  "mimo",
  "mirinae",
  "myexpenses",
  "myfitnesspal",
  "niagara-launcher",
  "nomone-desktop",
  "nova-launcher",
  "pandora",
  "podcast-addict",
  "prime-video",
  "proton-vpn",
  "pydroid3",
  "rp-hypertrophy",
  "showly",
  "sleep-as-android",
  "smart-launcher",
  "snorelab",
  "sofascore",
  "solid-explorer",
  "soundcloud",
  "teuida",
  "ttmik-stories",
  "ventusky",
  "wallcraft",
  "windy",
  "world-map-quiz",
  "wps-office",
  "xodo",
  "xrecorder",
]);

export const appConfigs = externalPatchAppConfigs([
  ["adguard", "AdGuard", "com.adguard.android"],
  ["alltrails", "AllTrails", "com.alltrails.alltrails"],
  ["avocards", "Avocards", "com.avocards"],
  ["busuu", "Busuu", "com.busuu.android.enc"],
  ["cake", "Cake", "me.mycake"],
  ["camscanner", "CamScanner", "com.intsig.camscanner"],
  ["daily-pocket", "Daily Pocket", "kr.co.yjteam.dailypay"],
  ["duolingo", "Duolingo", "com.duolingo"],
  ["eggbun", "Eggbun", "kr.eggbun.eggconvo"],
  ["fotmob", "FotMob", "com.mobilefootie.wc2010"],
  ["github", "GitHub", "com.github.android"],
  ["hellochinese", "HelloChinese", "com.hellochinese"],
  ["ibispaint-x", "IbisPaint X", "jp.ne.ibis.ibispaintx.app"],
  ["icon-packer", "Icon Packer", "cn.ommiao.iconpacker"],
  ["lingory", "Lingory", "org.languageapp.lingory"],
  ["lyfta", "Lyfta", "com.lyfta"],
  ["macrofactor", "MacroFactor", "com.sbs.diet"],
  ["macrofactor-workouts", "MacroFactor Workouts", "com.sbs.train"],
  ["meme-generator", "Meme Generator", "com.zombodroid.MemeGenerator"],
  ["merriam-webster", "Merriam-Webster", "com.merriamwebster"],
  ["mimo", "Mimo", "com.getmimo"],
  ["mirinae", "Mirinae", "com.mirinae.mirinae"],
  ["myexpenses", "MyExpenses", "org.totschnig.myexpenses"],
  ["myfitnesspal", "MyFitnessPal", "com.myfitnesspal.android"],
  ["niagara-launcher", "Niagara Launcher", "bitpit.launcher"],
  ["nomone-desktop", "NOMone Desktop", "nom.vrd"],
  ["nova-launcher", "Nova Launcher", "com.teslacoilsw.launcher"],
  ["pandora", "Pandora", "com.pandora.android"],
  ["podcast-addict", "Podcast Addict", "com.bambuna.podcastaddict"],
  ["prime-video", "Prime Video", "com.amazon.avod.thirdpartyclient"],
  ["proton-vpn", "Proton VPN", "ch.protonvpn.android", {
    apkmirrorOrg: "proton-technologies-ag",
    apkmirrorRepo: "protonvpn-secure-and-free-vpn",
    apkmirrorSlug: "proton-vpn-fast-secure-vpn",
    apkmirrorType: "bundle",
    apkmirrorFallbackArch: "universal",
    apkmirrorDpi: "120-640dpi",
  }],
  ["pydroid3", "PyDroid3", "ru.iiec.pydroid3"],
  ["rp-hypertrophy", "RP Hypertrophy", "com.rp.hypertrophy"],
  ["showly", "Showly", "com.michaldrabik.showly2"],
  ["sleep-as-android", "Sleep as Android", "com.urbandroid.sleep"],
  ["smart-launcher", "Smart Launcher", "ginlemon.flowerfree"],
  ["snorelab", "SnoreLab", "com.snorelab.app"],
  ["sofascore", "Sofascore", "com.sofascore.results"],
  ["solid-explorer", "Solid Explorer", "pl.solidexplorer2"],
  ["soundcloud", "SoundCloud", "com.soundcloud.android"],
  ["teuida", "Teuida", "net.teuida.teuida"],
  ["ttmik-stories", "TTMIK Stories", "app.ttmikstories.android"],
  ["ventusky", "Ventusky", "cz.ackee.ventusky"],
  ["wallcraft", "Wallcraft", "com.wallpaperscraft.wallpaper"],
  ["windy", "Windy", "com.windyty.android"],
  ["world-map-quiz", "World Map Quiz", "com.qbis.guessthecountry"],
  ["wps-office", "WPS Office", "cn.wps.moffice_eng"],
  ["xodo", "Xodo", "com.xodo.pdf.reader"],
  ["xrecorder", "XRecorder", "videoeditor.videorecorder.screenrecorder"],
]);

if (isMain) {
  const parsedTargets = parseTargets(env("BUILD_TARGETS") || "proton-vpn");

  validateTargets(command, parsedTargets, { supported: supportedTargets, family: "Hoodles" });

  const childEnv = {
    ...process.env,
    MORPHE_BUILDER: "hoodles",
    BUILD_TARGETS: parsedTargets.join(","),
    APK_SOURCE: env("APK_SOURCE") || "apkmirror,apkpure",
    APK_VERSION_SOURCE: "recommended",
    APK_LATEST_COMPATIBLE_ONLY: "",
    APK_FALLBACK_TO_LATEST: "false",
    APKMIRROR_ARCH: env("APKMIRROR_ARCH") || "arm64-v8a",
    MORPHE_ALLOW_UNIVERSAL_APKS_FOR_ABI: env("MORPHE_ALLOW_UNIVERSAL_APKS_FOR_ABI") || "0",
    MORPHE_PATCHES_PROVIDER: "github",
    MORPHE_PATCHES_REPO: env("HOODLES_PATCHES_REPO") || "hoo-dles/morphe-patches",
    MORPHE_PATCHES_VERSION: env("HOODLES_PATCHES_VERSION") || env("MORPHE_PATCHES_VERSION") || "stable",
    MORPHE_CREATE_DEFAULT_OPTIONS: env("MORPHE_CREATE_DEFAULT_OPTIONS") || "1",
    MORPHE_DISABLE_PACKAGE_RENAME_OPTIONS: env("MORPHE_DISABLE_PACKAGE_RENAME_OPTIONS") || "1",
  };

  applyDefaultPatchArgs(childEnv, command, { forcePatch: false });
  runMorphe({ root, command, args, childEnv, builderName: "hoodles" });
}
